spring:
  application:
    name: aaw
  devtools:
    restart:
      enabled: false  # Вимкнути restart для швидкого запуску
    livereload:
      enabled: false  # Вимкнути LiveReload

# Зменшити verbosity OpenCV логів
logging:
  level:
    root: INFO
    vyrib1.project.aaw: INFO

# Flags for hardware
features:
  gpio-buttons:
    enabled: false
  lrf:
    enabled: false
  camera:
    day-camera-enabled: true
    thermal-camera-enabled: false
  logger:
    enabled: false

